# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_Resultado.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_Resultado(object):
    def setupUi(self, Form_Resultado):
        Form_Resultado.setObjectName("Form_Resultado")
        Form_Resultado.resize(1600, 900)
        Form_Resultado.setMinimumSize(QtCore.QSize(1600, 900))
        Form_Resultado.setMaximumSize(QtCore.QSize(1600, 900))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form_Resultado.setPalette(palette)
        Form_Resultado.setWindowTitle("Simulador de Sistema Operativo")
        Form_Resultado.setAutoFillBackground(False)
        Form_Resultado.setStyleSheet("background-color: rgb(57, 57, 57);")
        Form_Resultado.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.pushButton_Siguiente = QtWidgets.QPushButton(Form_Resultado)
        self.pushButton_Siguiente.setGeometry(QtCore.QRect(1510, 30, 61, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_Siguiente.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_Siguiente.setFont(font)
        self.pushButton_Siguiente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Siguiente.setToolTip("")
        self.pushButton_Siguiente.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_Siguiente.setStyleSheet("background-color: rgb(0, 123, 255,150);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Siguiente.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Recursos/Siguiente.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Siguiente.setIcon(icon)
        self.pushButton_Siguiente.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Siguiente.setObjectName("pushButton_Siguiente")
        self.label = QtWidgets.QLabel(Form_Resultado)
        self.label.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.label.setBaseSize(QtCore.QSize(1600, 900))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Recursos/Fondo.jpg"))
        self.label.setObjectName("label")
        self.dockWidget = QtWidgets.QDockWidget(Form_Resultado)
        self.dockWidget.setGeometry(QtCore.QRect(260, 570, 1031, 321))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.tableWidget_Procesos = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableWidget_Procesos.setGeometry(QtCore.QRect(0, 0, 1031, 861))
        self.tableWidget_Procesos.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_Procesos.setFont(font)
        self.tableWidget_Procesos.setAutoFillBackground(False)
        self.tableWidget_Procesos.setStyleSheet("gridline-color: rgb(0,0, 0);\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);")
        self.tableWidget_Procesos.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tableWidget_Procesos.setLineWidth(1)
        self.tableWidget_Procesos.setMidLineWidth(0)
        self.tableWidget_Procesos.setAlternatingRowColors(True)
        self.tableWidget_Procesos.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_Procesos.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_Procesos.setShowGrid(True)
        self.tableWidget_Procesos.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_Procesos.setCornerButtonEnabled(False)
        self.tableWidget_Procesos.setRowCount(0)
        self.tableWidget_Procesos.setObjectName("tableWidget_Procesos")
        self.tableWidget_Procesos.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(9, item)
        self.tableWidget_Procesos.horizontalHeader().setVisible(True)
        self.tableWidget_Procesos.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_Procesos.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Procesos.verticalHeader().setHighlightSections(True)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.label.raise_()
        self.pushButton_Siguiente.raise_()
        self.dockWidget.raise_()

        self.retranslateUi(Form_Resultado)
        QtCore.QMetaObject.connectSlotsByName(Form_Resultado)

    def retranslateUi(self, Form_Resultado):
        _translate = QtCore.QCoreApplication.translate
        self.tableWidget_Procesos.setSortingEnabled(False)
        item = self.tableWidget_Procesos.horizontalHeaderItem(0)
        item.setText(_translate("Form_Resultado", "Tiempo"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(1)
        item.setText(_translate("Form_Resultado", "Listo"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(2)
        item.setText(_translate("Form_Resultado", "Bloqueado"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(3)
        item.setText(_translate("Form_Resultado", "Ejecución"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(4)
        item.setText(_translate("Form_Resultado", "Cola de Listos"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(5)
        item.setText(_translate("Form_Resultado", "Cola de Entrada"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(6)
        item.setText(_translate("Form_Resultado", "Cola de Salida"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(7)
        item.setText(_translate("Form_Resultado", "CPU"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(8)
        item.setText(_translate("Form_Resultado", "Entrada"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(9)
        item.setText(_translate("Form_Resultado", "Salida"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Resultado = QtWidgets.QWidget()
    ui = Ui_Form_Resultado()
    ui.setupUi(Form_Resultado)
    Form_Resultado.show()
    sys.exit(app.exec_())

