# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_CargaDeTrabajo.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_CargaDeTrabajo(object):
    def setupUi(self, Form_CargaDeTrabajo):
        Form_CargaDeTrabajo.setObjectName("Form_CargaDeTrabajo")
        Form_CargaDeTrabajo.resize(1024, 576)
        Form_CargaDeTrabajo.setMinimumSize(QtCore.QSize(1024, 576))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 57, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form_CargaDeTrabajo.setPalette(palette)
        Form_CargaDeTrabajo.setWindowTitle("Simulador de Sistema Operativo")
        Form_CargaDeTrabajo.setAutoFillBackground(False)
        Form_CargaDeTrabajo.setStyleSheet("background-color: rgb(57, 57, 57);")
        Form_CargaDeTrabajo.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.pushButton_Importar = QtWidgets.QPushButton(Form_CargaDeTrabajo)
        self.pushButton_Importar.setGeometry(QtCore.QRect(880, 240, 81, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_Importar.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("12 MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_Importar.setFont(font)
        self.pushButton_Importar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Importar.setStyleSheet("background-color: rgb(0, 123, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Importar.setAutoDefault(False)
        self.pushButton_Importar.setObjectName("pushButton_Importar")
        self.pushButton_Generar = QtWidgets.QPushButton(Form_CargaDeTrabajo)
        self.pushButton_Generar.setGeometry(QtCore.QRect(880, 360, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Generar.setFont(font)
        self.pushButton_Generar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Generar.setStyleSheet("background-color: rgb(0, 123, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Generar.setObjectName("pushButton_Generar")
        self.pushButton_Guardar = QtWidgets.QPushButton(Form_CargaDeTrabajo)
        self.pushButton_Guardar.setGeometry(QtCore.QRect(880, 300, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Guardar.setFont(font)
        self.pushButton_Guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Guardar.setStyleSheet("background-color: rgb(0, 123, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Guardar.setObjectName("pushButton_Guardar")
        self.tableWidget_Procesos = QtWidgets.QTableWidget(Form_CargaDeTrabajo)
        self.tableWidget_Procesos.setGeometry(QtCore.QRect(200, 150, 651, 351))
        self.tableWidget_Procesos.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_Procesos.setFont(font)
        self.tableWidget_Procesos.setAutoFillBackground(False)
        self.tableWidget_Procesos.setStyleSheet("gridline-color: rgb(0,0, 0);\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);")
        self.tableWidget_Procesos.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tableWidget_Procesos.setLineWidth(1)
        self.tableWidget_Procesos.setMidLineWidth(0)
        self.tableWidget_Procesos.setAlternatingRowColors(True)
        self.tableWidget_Procesos.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_Procesos.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_Procesos.setShowGrid(True)
        self.tableWidget_Procesos.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_Procesos.setCornerButtonEnabled(False)
        self.tableWidget_Procesos.setRowCount(0)
        self.tableWidget_Procesos.setObjectName("tableWidget_Procesos")
        self.tableWidget_Procesos.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Procesos.setHorizontalHeaderItem(5, item)
        self.tableWidget_Procesos.horizontalHeader().setVisible(True)
        self.tableWidget_Procesos.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_Procesos.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Procesos.verticalHeader().setHighlightSections(True)
        self.radioButton_ROUNDROBIN = QtWidgets.QRadioButton(Form_CargaDeTrabajo)
        self.radioButton_ROUNDROBIN.setGeometry(QtCore.QRect(40, 290, 101, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_ROUNDROBIN.setFont(font)
        self.radioButton_ROUNDROBIN.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_ROUNDROBIN.setObjectName("radioButton_ROUNDROBIN")
        self.label_CargaDeTrabajo = QtWidgets.QLabel(Form_CargaDeTrabajo)
        self.label_CargaDeTrabajo.setGeometry(QtCore.QRect(430, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_CargaDeTrabajo.setFont(font)
        self.label_CargaDeTrabajo.setStyleSheet("color: rgb(0, 123, 255);")
        self.label_CargaDeTrabajo.setObjectName("label_CargaDeTrabajo")
        self.radioButton_SRTF = QtWidgets.QRadioButton(Form_CargaDeTrabajo)
        self.radioButton_SRTF.setGeometry(QtCore.QRect(40, 260, 101, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_SRTF.setFont(font)
        self.radioButton_SRTF.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_SRTF.setObjectName("radioButton_SRTF")
        self.radioButton_FCFS = QtWidgets.QRadioButton(Form_CargaDeTrabajo)
        self.radioButton_FCFS.setGeometry(QtCore.QRect(40, 200, 101, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_FCFS.setFont(font)
        self.radioButton_FCFS.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_FCFS.setObjectName("radioButton_FCFS")
        self.radioButton_SJF = QtWidgets.QRadioButton(Form_CargaDeTrabajo)
        self.radioButton_SJF.setGeometry(QtCore.QRect(40, 230, 101, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_SJF.setFont(font)
        self.radioButton_SJF.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_SJF.setObjectName("radioButton_SJF")
        self.pushButton_Siguiente = QtWidgets.QPushButton(Form_CargaDeTrabajo)
        self.pushButton_Siguiente.setGeometry(QtCore.QRect(950, 10, 61, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_Siguiente.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_Siguiente.setFont(font)
        self.pushButton_Siguiente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Siguiente.setToolTip("")
        self.pushButton_Siguiente.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_Siguiente.setStyleSheet("background-color: rgb(0, 123, 255,150);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Siguiente.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Recursos/Siguiente.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Siguiente.setIcon(icon)
        self.pushButton_Siguiente.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Siguiente.setObjectName("pushButton_Siguiente")
        self.pushButton_Atras = QtWidgets.QPushButton(Form_CargaDeTrabajo)
        self.pushButton_Atras.setEnabled(False)
        self.pushButton_Atras.setGeometry(QtCore.QRect(10, 10, 61, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_Atras.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("12 MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_Atras.setFont(font)
        self.pushButton_Atras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Atras.setToolTip("")
        self.pushButton_Atras.setStyleSheet("background-color: rgb(0, 123, 150);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Atras.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Recursos/Atras.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Atras.setIcon(icon1)
        self.pushButton_Atras.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Atras.setAutoDefault(False)
        self.pushButton_Atras.setObjectName("pushButton_Atras")
        self.lineEdit_Quantum = QtWidgets.QLineEdit(Form_CargaDeTrabajo)
        self.lineEdit_Quantum.setEnabled(True)
        self.lineEdit_Quantum.setGeometry(QtCore.QRect(100, 320, 41, 20))
        self.lineEdit_Quantum.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Quantum.setText("")
        self.lineEdit_Quantum.setMaxLength(3)
        self.lineEdit_Quantum.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Quantum.setObjectName("lineEdit_Quantum")
        self.label_Quantum = QtWidgets.QLabel(Form_CargaDeTrabajo)
        self.label_Quantum.setGeometry(QtCore.QRect(40, 320, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Quantum.setFont(font)
        self.label_Quantum.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Quantum.setObjectName("label_Quantum")
        self.groupBox_Algoritmo = QtWidgets.QGroupBox(Form_CargaDeTrabajo)
        self.groupBox_Algoritmo.setGeometry(QtCore.QRect(30, 160, 151, 201))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Algoritmo.setFont(font)
        self.groupBox_Algoritmo.setStyleSheet("color: rgb(0, 123, 255);")
        self.groupBox_Algoritmo.setObjectName("groupBox_Algoritmo")
        self.label_NProcesos = QtWidgets.QLabel(Form_CargaDeTrabajo)
        self.label_NProcesos.setGeometry(QtCore.QRect(200, 110, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_NProcesos.setFont(font)
        self.label_NProcesos.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_NProcesos.setObjectName("label_NProcesos")
        self.lineEdit_NProcesos = QtWidgets.QLineEdit(Form_CargaDeTrabajo)
        self.lineEdit_NProcesos.setGeometry(QtCore.QRect(340, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_NProcesos.setFont(font)
        self.lineEdit_NProcesos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_NProcesos.setText("")
        self.lineEdit_NProcesos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_NProcesos.setClearButtonEnabled(False)
        self.lineEdit_NProcesos.setObjectName("lineEdit_NProcesos")
        self.groupBox_Algoritmo.raise_()
        self.pushButton_Importar.raise_()
        self.pushButton_Generar.raise_()
        self.pushButton_Guardar.raise_()
        self.tableWidget_Procesos.raise_()
        self.radioButton_ROUNDROBIN.raise_()
        self.label_CargaDeTrabajo.raise_()
        self.radioButton_SRTF.raise_()
        self.radioButton_FCFS.raise_()
        self.radioButton_SJF.raise_()
        self.pushButton_Siguiente.raise_()
        self.pushButton_Atras.raise_()
        self.lineEdit_Quantum.raise_()
        self.label_Quantum.raise_()
        self.label_NProcesos.raise_()
        self.lineEdit_NProcesos.raise_()
        self.label_Quantum.setBuddy(self.lineEdit_Quantum)
        self.label_NProcesos.setBuddy(self.lineEdit_NProcesos)

        self.retranslateUi(Form_CargaDeTrabajo)
        self.pushButton_Siguiente.clicked.connect(Form_CargaDeTrabajo.close)
        QtCore.QMetaObject.connectSlotsByName(Form_CargaDeTrabajo)
        Form_CargaDeTrabajo.setTabOrder(self.lineEdit_NProcesos, self.radioButton_FCFS)
        Form_CargaDeTrabajo.setTabOrder(self.radioButton_FCFS, self.radioButton_SJF)
        Form_CargaDeTrabajo.setTabOrder(self.radioButton_SJF, self.radioButton_SRTF)
        Form_CargaDeTrabajo.setTabOrder(self.radioButton_SRTF, self.radioButton_ROUNDROBIN)
        Form_CargaDeTrabajo.setTabOrder(self.radioButton_ROUNDROBIN, self.lineEdit_Quantum)
        Form_CargaDeTrabajo.setTabOrder(self.lineEdit_Quantum, self.tableWidget_Procesos)
        Form_CargaDeTrabajo.setTabOrder(self.tableWidget_Procesos, self.pushButton_Importar)
        Form_CargaDeTrabajo.setTabOrder(self.pushButton_Importar, self.pushButton_Guardar)
        Form_CargaDeTrabajo.setTabOrder(self.pushButton_Guardar, self.pushButton_Generar)
        Form_CargaDeTrabajo.setTabOrder(self.pushButton_Generar, self.pushButton_Siguiente)
        Form_CargaDeTrabajo.setTabOrder(self.pushButton_Siguiente, self.pushButton_Atras)

    def retranslateUi(self, Form_CargaDeTrabajo):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_Importar.setToolTip(_translate("Form_CargaDeTrabajo", "<html><head/><body><p>Importar carga de trabajo</p></body></html>"))
        self.pushButton_Importar.setText(_translate("Form_CargaDeTrabajo", "Importar"))
        self.pushButton_Generar.setToolTip(_translate("Form_CargaDeTrabajo", "<html><head/><body><p>Generar una carga de trabajo aleatoria</p></body></html>"))
        self.pushButton_Generar.setText(_translate("Form_CargaDeTrabajo", "Generar"))
        self.pushButton_Guardar.setToolTip(_translate("Form_CargaDeTrabajo", "<html><head/><body><p>Guardar la carga de trabajo actual</p></body></html>"))
        self.pushButton_Guardar.setText(_translate("Form_CargaDeTrabajo", "Guardar"))
        self.tableWidget_Procesos.setSortingEnabled(False)
        item = self.tableWidget_Procesos.horizontalHeaderItem(0)
        item.setText(_translate("Form_CargaDeTrabajo", "Tiempo de Arribo"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(1)
        item.setText(_translate("Form_CargaDeTrabajo", "CPU"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(2)
        item.setText(_translate("Form_CargaDeTrabajo", "Entrada"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(3)
        item.setText(_translate("Form_CargaDeTrabajo", "CPU"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(4)
        item.setText(_translate("Form_CargaDeTrabajo", "Salida"))
        item = self.tableWidget_Procesos.horizontalHeaderItem(5)
        item.setText(_translate("Form_CargaDeTrabajo", "CPU"))
        self.radioButton_ROUNDROBIN.setText(_translate("Form_CargaDeTrabajo", "ROUND ROBIN"))
        self.label_CargaDeTrabajo.setText(_translate("Form_CargaDeTrabajo", "Carga de Trabajo"))
        self.radioButton_SRTF.setToolTip(_translate("Form_CargaDeTrabajo", "Short Remaining Time First"))
        self.radioButton_SRTF.setText(_translate("Form_CargaDeTrabajo", "SRTF"))
        self.radioButton_FCFS.setToolTip(_translate("Form_CargaDeTrabajo", "First Come, First Served"))
        self.radioButton_FCFS.setText(_translate("Form_CargaDeTrabajo", "FCFS"))
        self.radioButton_SJF.setToolTip(_translate("Form_CargaDeTrabajo", "Shortest Job First"))
        self.radioButton_SJF.setText(_translate("Form_CargaDeTrabajo", "SJF"))
        self.lineEdit_Quantum.setInputMask(_translate("Form_CargaDeTrabajo", "000"))
        self.label_Quantum.setText(_translate("Form_CargaDeTrabajo", "Quantum"))
        self.groupBox_Algoritmo.setTitle(_translate("Form_CargaDeTrabajo", "Algoritmo"))
        self.label_NProcesos.setText(_translate("Form_CargaDeTrabajo", "Nº de Procesos"))
        self.lineEdit_NProcesos.setInputMask(_translate("Form_CargaDeTrabajo", "000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_CargaDeTrabajo = QtWidgets.QWidget()
    ui = Ui_Form_CargaDeTrabajo()
    ui.setupUi(Form_CargaDeTrabajo)
    Form_CargaDeTrabajo.show()
    sys.exit(app.exec_())

